#!/bin/bash
# A script to run Taiwan eProcurement crawler
 
usage () {
    echo "Usage: eprocurement [[[--conf file] [--start YYYYmmdd] [--end YYYYmmdd] [--all] [--qa] [--qd] [--dl] [--load]] | [--help]]"
}

#### Main

conf_file="${PWD}/eprocurement.conf"
start_date=""
end_date=""
do_qa=false
do_qd=false
do_dl=false
do_load=false

while [ "$1" != "" ]; do
    case $1 in
        --conf )     shift
                     conf_file=$1
                     ;;
        --start )    shift
                     start_date=$1
                     ;;
        --end )      shift
                     end_date=$1
                     ;;
        --all )      do_qa=true
                     do_qd=true
                     do_dl=true
                     do_load=true
                     ;;
        --qa )       do_qa=true
                     ;;
        --qd )       do_qd=true
                     ;;
        --dl )       do_dl=true
                     ;;
        --load )     do_load=true
                     ;;
        --help )     usage
                     exit
                     ;;
        * )          usage
                     exit 1
    esac
    shift
done

source $conf_file
printf "eProcurement crawler configuration:\n"
printf "  Python:              %s\n" "$python_exec"
printf "  Crawler path:        %s\n" "$crawler_path"
printf "  Archive list dir     %s\n" "$archive_list_dir"
printf "  Awarded queryer:     %s\n" "$queryer_awarded"
printf "  Declaration queryer: %s\n" "$queryer_declaration"
printf "  Downloader:          %s\n" "$downloader"
printf "  Loader:              %s\n" "$loader"
printf "  Dataset path:        %s\n" "$dataset_path"
printf "  Awarded prefix:      %s\n" "$prefix_awarded"
printf "  Declaration prefix:  %s\n" "$prefix_declaration"
printf "  DB user name:        %s\n" "$db_user"
printf "  DB password:         %s\n" "$db_password"
printf "  DB host:             %s\n" "$db_host"
printf "  DB database name:    %s\n" "$db_database"
printf "  Proxy:               %s\n" "$proxy"
printf "  Parallel (download): %s\n" "$parallel_downloader"
printf "  Parallel (loader):   %s\n" "$parallel_loader"
printf "  Max retry:           %s\n" "$max_retry"
printf "  Last update date:    %s\n" "$last_update"
printf "\n"

if [ "$start_date" == "" ]; then
    start_date=$(date -d "$last_update +1 days" +"%Y%m%d")
fi

if [ "$end_date" == "" ]; then
    end_date=$(date -d "-1 days" +"%Y%m%d")
    last_update="$end_date"
fi

if [ "$max_retry" == "" ]; then
    max_retry=10
fi

file_awarded="$dataset_path${prefix_awarded}_${start_date}_${end_date}.txt"
file_awarded_dl_err="${file_awarded}.download.err"
dir_awarded="$dataset_path${prefix_awarded}_${start_date}_${end_date}"
file_declaration="$dataset_path${prefix_declaration}_${start_date}_${end_date}.txt"
file_declaration_dl_err="${file_declaration}.download.err"
dir_declaration="$dataset_path${prefix_declaration}_${start_date}_${end_date}"
printf "Output files and directories:\n"
if [ "$do_qa" == true ]; then
    printf "  Awarded bid list: %s\n" "$file_awarded"
fi
if [ "$do_dl" == true ]; then
    printf "  Awarded bid directory: %s\n" "$dir_awarded"
fi
if [ "$do_qd" == true ]; then
    printf "  Declaration bid list: %s\n" "$file_declaration"
fi
if [ "$do_dl" == true ]; then
    printf "  Declaration bid directory: %s\n" "$dir_declaration"
fi
printf "\n"

queryer_awarded_fp="$crawler_path$queryer_awarded"
queryer_declaration_fp="$crawler_path$queryer_declaration"
downloader_fp="$crawler_path$downloader"
loader_fp="$crawler_path$loader"

mkdir -p "$archive_list_dir"
if [ "$do_qa" == true ]; then
    echo "Start queryer (awarded)..."
    $python_exec $queryer_awarded_fp -s $start_date \
                                     -e $end_date \
                                     -f $file_awarded
    cp "$file_awarded" "$archive_list_dir"
fi

if [ "$do_qd" == true ]; then
    echo "Start queryer (declaration)..."
    $python_exec $queryer_declaration_fp -s $start_date \
                                         -e $end_date \
                                         -f $file_declaration
    cp "$file_declaration" "$archive_list_dir"
fi

if [ "$do_dl" == true ]; then
    dl_flag=true
    cur_retry=0
    while [ "$dl_flag" == true -a "$cur_retry" -lt "$max_retry" ]
    do
        if [ -f "$file_awarded" ]; then
            echo "Start downloader (awarded)..."
            if [ "$proxy" != "" ]; then
                $python_exec $downloader_fp -f $file_awarded -d $dir_awarded -x $proxy -p $parallel_downloader
            else
                $python_exec $downloader_fp -f $file_awarded -d $dir_awarded -p $parallel_downloader
            fi
        fi

        if [ -f "$file_declaration" ]; then
            echo "Start downloader (declaration)..."
            if [ "$proxy" != "" ]; then
                $python_exec $downloader_fp -f $file_declaration -d $dir_declaration -x $proxy -p $parallel_downloader
            else
                $python_exec $downloader_fp -f $file_declaration -d $dir_declaration -p $parallel_downloader
            fi
        fi

        dl_flag=false
        if [ -f "$file_awarded_dl_err" ]; then
            mv "$file_awarded_dl_err" "$file_awarded"
            dl_flag=true
        fi
        if [ -f "$file_declaration_dl_err" ]; then
            mv "$file_declaration_dl_err" "$file_declaration"
            dl_flag=true
        fi

        printf "Total retry count: %s\n" "$cur_retry"
        cur_retry=$(($cur_retry + 1))
    done
fi

if [ "$do_load" == true ]; then
    if [ -d "$dir_awarded" ]; then
        echo "Start loader (awarded)..."
        $python_exec $loader_fp -d $dir_awarded -u $db_user -p $db_password -i $db_host -b $db_database -l $parallel_loader
    fi

    if [ -d "$dir_declaration" ]; then
        echo "Start loader (declaration)..."
        $python_exec $loader_fp -a -d $dir_declaration -u $db_user -p $db_password -i $db_host -b $db_database -l $parallel_loader
    fi
fi

cat > "$conf_file" <<EOF
python_exec="$python_exec"
crawler_path="$crawler_path"
archive_list_dir="$archive_list_dir"
queryer_awarded="$queryer_awarded"
queryer_declaration="$queryer_declaration"
downloader="$downloader"
loader="$loader"
dataset_path="$dataset_path"
prefix_awarded="$prefix_awarded"
prefix_declaration="$prefix_declaration"
proxy="$proxy"
parallel_downloader="$parallel_downloader"
parallel_loader="$parallel_loader"
max_retry="$max_retry"
db_user="$db_user"
db_password="$db_password"
db_host="$db_host"
db_database="$db_database"
last_update="$last_update"
EOF
